# Generated by Django 4.2.2 on 2023-07-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
